spring:
  application:
    name: donorsearch-backend
  datasource:
    url: jdbc:postgresql://192.168.0.27:5432/hackathon
    username: nova
    password: j0cVbLlNpuwx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    bot:
      token: "6628063981:AAEUuBlxYOGwPrJyvoi3R0_COaF6O4kKKf0"
      name: "donorsearch_opengamer_bot"
    uri:
      auth:
        reg: "https://api2.donorsearch.org/api/auth/registration/"
        login: "https://api2.donorsearch.org/api/auth/login/"
        confirm-email: "https://api2.donorsearch.org/api/auth/confirm_email_reg/"
        confirm-phone: "https://api2.donorsearch.org/api/auth/confirm_phone_reg/"
      donation:
        donation-plan: "https://api2.donorsearch.org/api/donation_plan/"

